version: '3.8'
services:
  mongo:
    image: mongo:latest
    ports:
      - "27017:27017"

  api:
    build: .
    ports:
      - "5001:5000"  # Mengubah port dari 5000:5000 menjadi 5001:5000
    depends_on:
      - mongo
